### ISSUE TITLE
Unable to debug tests in sub directories

### ISSUE THREAD

**Issue by sourcier** [hbenl/vscode-mocha-test-adapter#1]
I get the following error when I try to debug tests for a component in a sub dir:

    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rrajaratnam/.vscode/extensions/hbenl.vscode-mocha-test-adapter-0.4.1/out/worker/runTests.js:19:5)
    at Module._compile (module.js:649:14)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Waiting for the debugger to disconnect...

My config:
"mochaExplorer.cwd": "app",
"mochaExplorer.require": [
    "ts-node/register"
],
"mochaExplorer.files": "app/test/**/*spec.ts",

I believe this is being caused by the mochaExplorer.cwd option not being honoured in the debug run, as tests work fine when not debugging.

**Comment by hbenl** [comment]
This is actually the correct repository for this bug report

**Comment by hbenl** [comment]
Fixed in version 0.4.2

**Comment by sourcier** [comment]
There error is no longer happening, however none of my break points are being hit.

**Comment by hbenl** [comment]
I found a possible reason: in a project that uses `mochaExplorer.require` like you do, I had to change the value of `mochaExplorer.require` to `../node_modules/ts-node/register` as soon as I added `mochaExplorer.cwd`. Otherwise I couldn't even _load_ the tests anymore. Could you try if this workaround works for you?

**Comment by sourcier** [comment]
I’m not sure if this will work in my case, the node_modules folder is in my app sub directory. I will try your suggestion and report back.

**Comment by hbenl** [comment]
In that case you could try to set it to `./node_modules/ts-node/register` or `node_modules/ts-node/register`.
Furthermore I'd be interested if you can still _run_ the tests even if you can't _debug_ them (because I guess that if breakpoints are not hit then the test isn't run in the debugger at all).

**Comment by sourcier** [comment]
I tried my tests again, and some are working fine and others are failing, the ones that are failing have underlaying dependency issues, the extension is not at fault.
