### ISSUE TITLE
Spawning multiple node processes

### ISSUE THREAD

**Issue by denis-osipov** [hbenl/vscode-mocha-test-adapter#104]
I have an issue with spawning multiple node processes by  vscode-mocha-test-adapter even when I don't run any tests. If wait long enough (not too long if run tests) node processes occupy all free memory.
In other respects extension works fine.

![image](https://user-images.githubusercontent.com/24683226/80588204-53ab7e80-8a31-11ea-8a88-c6dda7f1a86e.png)

Mocha Test Explorer 2.3.0
Test Explorer UI 2.18.0
Visual Studio Code 1.44.2
Mocha 7.1.1
Node 13.12.0 through nvm 0.35.3
Ubuntu 19.10

**Comment by hbenl** [comment]
This probably happens because your tests contain some code that prevents the node process from exiting (e.g. a Promise that is never resolved). Even if you don't run any tests, by default the extension will reload the tests every time you edit the code and a new node process is spawned for every reload.
If my guess is correct, this could be easily fixed by adding `"mochaExplorer.exit": true` to your settings.

**Comment by denis-osipov** [comment]
Thank you:) Setting `"mochaExplorer.exit": true` solved my problem.
