### ISSUE TITLE
Not setting UI methods on require('mocha')

### ISSUE THREAD

**Issue by cspotcode** [hbenl/vscode-mocha-test-adapter#11]
I normally access `describe` and `it` via `const {describe, it} = require('mocha');` in my test suites.  However, vscode-mocha-test-adapter is not using the version of mocha I have installed in node_modules.  It's using its own, bundled version.  Therefore, the UI methods are not being set and I can't access them.

Can this extension be updated to use the version of Mocha I have locally installed in my project?

**Comment by cspotcode** [comment]
I'm using the latest version.  I don't think it's a well-documented feature
but it's been there for a while.

That's a good point about compatibility.  If you're monkey-patching the
"interfaces" then I think that's pretty safe, since the interface API
hasn't changed in a while.  Also interfaces are made to be pluggable.

**Comment by hbenl** [comment]
Thanks, I was confused at first because mocha initially doesn't export the UI methods. But I understand now that they are added to the exports dynamically in a `pre-require` hook.

My concern about compatibility was that if you use the UI methods from mocha's exports (instead of using the ones added to node's globals), you might end up using the unpatched versions of these methods. But since the patch is applied before mocha is run (and hence before the `pre-require` hook), this should actually work.

I'll add an option the specify the mocha version to use.

**Comment by cspotcode** [comment]
Oh I understand, makes sense.  Thank you!

**Comment by hbenl** [comment]
OK, if you upgrade to version 1.3.0 and add `"mochaExplorer.mochaPath": "node_modules/mocha"` to your settings, it should work :)
