### ISSUE TITLE
`ts-node` 8.10 puts CodeLens run commands in the wrong place

### ISSUE THREAD

**Issue by sgranade** [hbenl/vscode-mocha-test-adapter#111]
I recently upgraded `ts-node` from 8.9.1 to 8.10.0 in my project. When I did that, CodeLens started putting the run commands in the entirely wrong places.

With `ts-node` 8.9.1, the CodeLens run locations are correct:
![8 9_corrent_codelens](https://user-images.githubusercontent.com/238926/82504690-978a2480-9ac1-11ea-956b-fffb6e8a9717.png)

However, if I upgrade `ts-node` to 8.10.0 or 8.10.1, then the CodeLens run locations are wrong.

![8 10_incorrect_codelens](https://user-images.githubusercontent.com/238926/82504763-cb654a00-9ac1-11ea-96ec-2c42e702d589.png)

The tests appear to run correctly, but I can't tell what CodeLens "run" command goes with which test, and test failures are attached to the entirely wrong line.

![8 10_incorrect_test_result_location](https://user-images.githubusercontent.com/238926/82505009-5f371600-9ac2-11ea-9272-494b0e6d4326.png)

Any idea what might be going on?

**Comment by hbenl** [comment]
I'm guessing it is due to TypeStrong/ts-node#1055 for which they already have a fix, but it hasn't been published yet.
In the meantime you could try adding `"mochaExplorer.monkeyPatch": false` to your settings: this will switch to a more primitive mechanism for detecting the test locations. The standard mechanism uses stack traces to find the locations and those stack traces seem to have wrong line numbers due to the ts-node bug.

**Comment by hbenl** [comment]
The issue was fixed in ts-node 8.10.2.

**Comment by pcnova** [comment]
Just want to note that this issue also happens in later versions (mine is 9.1.1) if you happen to be using the `ts-node/esm` loader.

Setting `"mochaExplorer.monkeyPatch": false` still serves as a workaround in this case.

**Comment by tipy01** [comment]
I got this issue too but it is linked to the my node.js version

node.js : v18.18.2 -> v20.13.1

the problem appears with v20 (maybe ts-node/esm acts differently depending on the node.js version)

As previously noted `"mochaExplorer.monkeyPatch": false` may serve as workaround.
