### ISSUE TITLE
Documentation needed for how to resolve "No debug adapter, can not send 'variables'"

### ISSUE THREAD

**Issue by connerk** [hbenl/vscode-mocha-test-adapter#115]
when adding a console.log() that returns an object or array and running a debug through Mocha Test Adapter, details of the object or array are not presented. instead, it states:

 `No debug adapter, can not send 'variables' `

I would like to install a `debug adapter` in order to see objects while debugging, but am not clear what Mocha Test Explorer is talking about. 🤣 

If someone can point me in the right direction I would be grateful!

Great tool, by the way, I'm loving it!

**Comment by hbenl** [comment]
You already have the debug adapter installed, it's the standard javascript debugger. The error message should really say "Debug session has ended, can't fetch the object's properties anymore". 
The problem is that when `console.log` sends an object to the debug console in VS Code, the details aren't fetched from the debug session until you click on the chevron next to the object. But when the debug session has already ended, there is no more debug session to fetch that data from.
But if the debug session is still active (e.g. when you're stopped on some breakpoint), it should work.
