### ISSUE TITLE
Not recognizing tests...

### ISSUE THREAD

**Issue by mikeerickson** [hbenl/vscode-mocha-test-adapter#134]
I am trying out this extension for the first time and am curious how it recognizes tests?

I have a test structure `./spec` which has a large number tests which I normal invoke using

```js
./node_modules/mocha/bin/mocha spec --slow 500 --reporter mocha-better-spec-reporter
```

When I click on the `test` icon in the VSCode Explorer, nothing appears?

I have clicked the `reload tests` icon, but nothing ever appears?

**Comment by cblair** [comment]
I have the same issue.

**Comment by hbenl** [comment]
If you pass any options to mocha, you need to tell the extension about that. As the documentation states, you should put them in a mocha configuration file or in VS Code settings.
@mikeerickson since the extension doesn't know that your tests are in `./spec`, it can't load them
@cblair I'd need a bit more information - do you have a sample repo?

**Comment by PipsqueakH** [comment]
not working in yarn workspaces.
i have such project structure:
```
.
├── package.json
├── packages
│   ├── subProjA
│   │   ├── .mocharc.json
│   │   ├── node_modules
│   │   ├── package.json
│   │   ├── src
│   │   │   └── index.ts
│   │   ├── test
│   │   │   └── testA.test.ts
│   │   └── yarn.lock
│   └── subProjB
│       ├── node_modules
│       ├── package.json
│       ├── index.ts
│       └── yarn.lock
├── tsconfig.json
├── yarn-error.log
└── yarn.lock
```
in packages/subProjA/.mocharc.json:
```
{
    "extension": ["ts"],
    "spec": "./test/*.test.ts",
    "require": "ts-node/register/files",
    "timeout": 20000
}
```
and in folder packages/subProjA, i can run command:
`
yarn exec mocha test
`

but the plugin can not recognize the tests.

ps. it works without yarn worksapces.

**Comment by hbenl** [comment]
@PipsqueakH The reason is that this extension expects `.mocharc.json` in the root folder of your workspace.
I'd recommend using [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) for this kind of project structure. That should make this extension work for your project (and additionally it gives you the ability to have different VS Code settings for your subprojects).
I am planning to make the `.mocharc.json` location configurable, you will then be able to make it work even without using a multi-root workspace.

**Comment by yairEO** [comment]
@hbenl - The README says you don't need `.mocharc.json` but can directly set this plugin's parameters through *vscode* `settings.json` file (and then they will apply globally) but even with that I have no luck in finding my tests :(

I was sure this plugin automatically shows on the sidebar all the tests found inside a file (tab) which is currently open in the IDE

**Comment by mikeerickson** [comment]
@PipsqueakH @yairEO @yairEO 

Did any of you ever find a solution for this?  I have it working in some projects, but other projects it does show a thing.  I have NO IDEA what the conflict is.  I have checked two recent projects (one that works, the other does not work).  They both have a `.mocharc.js` file in the root of the project.

**Comment by mikeerickson** [comment]
@hbenl I have figured out where to update this (by creating a workspace setting) and defining "mochaExplorer.files" value

```json
{
	"mochaExplorer.files": "specs/**/*test.js"
}
```

**Comment by yairEO** [comment]
Still not recognizing tests:

![image](https://user-images.githubusercontent.com/845031/153767864-6c6417fa-0dd7-44e9-b4ee-203d1cfb9c79.png)
