### ISSUE TITLE
Problem with output and native Testing UI

### ISSUE THREAD

**Issue by Drarig29** [hbenl/vscode-mocha-test-adapter#178]
In the latest release of VS Code (July 2021, version 1.59) the Testing API was finalized.
We can now use the `testExplorer.useNativeTesting` setting to disable the Test Explorer UI extension and use the native Testing UI instead.

The problem is that the new "Peek error" button does not show errors of failing tests.

And the output channel "Mocha Tests" is not updated either.

- Some documentation: https://code.visualstudio.com/api/extension-guides/testing
- An extension which was updated recently to use the native API: https://github.com/Microsoft/vscode-java-test

**Comment by hbenl** [comment]
See Microsoft/vscode-test-adapter-converter#17

**Comment by rickstaa** [comment]
@hbenl Any update on this? It looks like https://github.com/microsoft/vscode/issues/129201 has been released.

**Comment by Drarig29** [comment]
Yes it works now. Closing the issue.

**Comment by rickstaa** [comment]
Amazing!

**Comment by rickstaa** [comment]
@Drarig29, @hbenl The only thing left to do is to remove the dependency to the extension see #183.

**Comment by hbenl** [comment]
@rickstaa No, that's not how it works: this extension still needs the Test Explorer extension, but when you have native testing enabled, the Test Explorer extension will not show its own UI and instead will only pass the tests to the native testing API. To get rid of the dependency on the Test Explorer extension, this extension would need to be partially rewritten so that it talks to the native testing API (instead of the old Test Explorer API) directly. I may do that eventually but there's no rush: Test Explorer won't go away and as long as this extension doesn't need any of the additional capabilities of the native testing API, there's no benefit in doing this rewrite.

**Comment by rickstaa** [comment]
@hbenl No problem I already was afraid that that was the case. I however was just looking to clean up my extensions. I will keep the test explorer extension for now.
