### ISSUE TITLE
"Cancel Running Tests" button remains after running all tests

### ISSUE THREAD

**Issue by kakins** [hbenl/vscode-mocha-test-adapter#179]
Not sure if this is something with the adapter or something with my tests, but the behavior appears to be new
![image](https://user-images.githubusercontent.com/14915247/131525539-0d56ef6f-df42-45c1-a456-48f909fc49bd.png)

The button remains after all my tests have completed.  I'm not sure how to diagnose.

**Comment by hbenl** [comment]
This happens if the child process that's running the tests doesn't exit at the end of the test run. You can solve this using the `mochaExplorer.exit` option, which corresponds to Mocha's [`--exit`](https://mochajs.org/#-exit) option. The recommended fix, however, is to find out what's causing the process to "hang" (which can be difficult though).

**Comment by kakins** [comment]
@hbenl Thanks!  Yeah I found it, I had a connection to a queue that was left open and was not properly closed.  Afterwards tests ended as expected :)
