### ISSUE TITLE
Why do my tests have warning icons against them? 🤔

### ISSUE THREAD

**Issue by garrytrinder** [hbenl/vscode-mocha-test-adapter#185]
I'm testing out this extension on CLI for Microsoft 365 to make it easier from contributors to execute tests, https://github.com/pnp/cli-microsoft365/issues/2817, whilst most tests are fine, there are a few tests that cannot be executed displaying a grey warning icon, example shown below. 

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/11563347/144682392-12b92372-9bae-44f6-8b01-79ba08ff0192.png">

I'm not able to find any debug logs to explain what the issue is. The two tests shown in the screenshot above don't seem to be much different, anyone know what is going on here?

**Comment by garrytrinder** [comment]
Anyone? ✋🏻

**Comment by hbenl** [comment]
The tests have the same label and since that label is the only way for the test adapter to identify a test, it doesn't know which test is meant when it receives a test result for one of those tests - hence the warning.
When you hover over one of these tests, VS Code also shows a tooltip with a short explanation.

**Comment by garrytrinder** [comment]
Ah yes of course, thank you @hbenl appreciate the update 👍
