### ISSUE TITLE
Approx 3 second delay in completing a few tests, non with command line equivalent

### ISSUE THREAD

**Issue by David-Else** [hbenl/vscode-mocha-test-adapter#29]
Hi,

I have compared running mocha on the command line with:

`mocha --watch --reporter min --require esm --require jsdom-global/register`

and using the test adapter with these settings added in vs code settings:

`"mochaExplorer.require": ["esm", "jsdom-global/register"],`

The command line results are instant, as soon as I save a test file it updates. The test adapter takes about 3 seconds.  It cycles between red, blue, green slowly. Is there any way to speed this up? Thanks.

**Comment by hbenl** [comment]
The delay is somewhere in your setup script - so it also happens when Mocha is run on the command line, but only once, because `mocha --watch` will not run the setup script again when the tests have changed.

Unfortunately, this is not possible with the way that this extension works: it creates a new child process for running Mocha every time that tests are run, so the setup script has to be run again :(
