### ISSUE TITLE
'Run' runs all tests with the same name

### ISSUE THREAD

**Issue by d-andrii** [hbenl/vscode-mocha-test-adapter#46]
If you click on 'Run' it runs all test with the same name even if tests are in different files. Works both in Test Explorer and with CodeLens.
If this is not a bug would be better to have the option to switch the behaviour.

**Comment by hbenl** [comment]
You can try adding `"mochaExplorer.pruneFiles": true` to your VS Code settings (you'll have to restart VS Code for this to take effect). However, that setting may break testing in some projects, that's why it is off by default. If it doesn't work in your project, there's nothing I can do: I can only tell Mocha the names of the tests that I want to run, if two tests have the same name, there is no way for me to tell Mocha which one to run.
