### ISSUE TITLE
how to run tests with electron dependency?

### ISSUE THREAD

**Issue by ssrakesh** [hbenl/vscode-mocha-test-adapter#66]
I have some testcases with electron dependencies . but because if this none of tests loaded in explorer. ("Error while loading tests - click to show" is shown)

most of the error is related to electron.app object.
`const whenReady = app.isReady()`

is there any way to load these tests? also once the error appears, further loading of tests will not happen.
Is there any way to continue loading testcases?

**Comment by hbenl** [comment]
How do you run the tests without the Test Explorer (i.e. on the command line)?

**Comment by ssrakesh** [comment]
> How do you run the tests without the Test Explorer (i.e. on the command line)?
Sorry I my question was not clear, I have modified now.
from command I can run tests using "npm test"

**Comment by hbenl** [comment]
Apparently my question wasn't clear either - I need the full configuration for your tests:
- the `test` script from your `package.json`
- mocha configuration file (if you have any, like `mocha.opts` or `.mocharc.json` or ...)
- mocha settings in `package.json` (if you have any)
- vscode settings for this adapter

In the meantime I discovered the other issue you opened (maty21/mocha-sidebar#200).
I noticed `"mocha.requires": [ "node_modules/electron" ]`, which seems odd to me, usually the value should be something that you can pass to the `require` function in javascript, i.e. it should probably be `"electron"` instead of `"node_modules/electron"`.
Also it seems very odd that you get the error `Cannot read property 'app' of undefined` for the line `let app = electron.app;` but the line `const shell = electron.shell;` doesn't seem to throw an error - no idea how that is possible.

**Comment by ssrakesh** [comment]
Thanks for replay.

I am not using exact configuration which was used in  (maty21/mocha-sidebar#200).
package.json test config
`"test": "electron-mocha ./test --colors  --inline-diffs --check-leaks --bail false --reporter mocha-jenkins-reporter --reporter-options junit_report_path=./build/mochaTestResults.xml "`

_"devDependencies": {
    "chai": "^4.2.0",
    "electron": "5.0.8",
    "electron-debug": "3.0.1",
    "electron-mocha": "^8.1.1",
    "electron-packager": "14.0.3",
    "electron-packager-languages": "^0.3.0",
    "electron-packager-plugin-non-proprietary-codecs-ffmpeg": "^1.0.2",
    "expect.js": "^0.3.1",
    "json": "^9.0.6",
    "mocha-jenkins-reporter": "^0.4.1",
    "mocha-junit-reporter": "^1.23.1"
  }_

I am not using any mocha.opts.

vscode settings
```
{
  "workbench.editor.enablePreview": false,
  "mochaExplorer.files": "test/**/*test.js",  
  "mochaExplorer.logpanel": true,  
  "mochaExplorer.pruneFiles": true,    
} 
```
I am not using "mocha.requires": [ "node_modules/electron" ] now,

Also I got issues when a included (using require) js file with class with member function having following format
```
someMethod = function (argument) {
...
}
```
the error was 
`SyntaxError: Unexpected token =
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)`

this got solved with changing the function format to
`
someMethod(argument) {
...
}
`

Issue is some dependent (used as require in test.js) file app object is used in file scope.
So I was able to get all the tests loaded by
1. moving the require of these files and object creation inside  it('') block of describe
2. removing code to refer app object, instead use it some function where its required.

**Comment by ssrakesh** [comment]
Also I tried to use `"mochaExplorer.require": "electron"` in vscode settings.
But this error started appearing
`
{ Error: Cannot find module 'f:\folder\project\src\electron'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at execute (C:\Users\USER1\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.1.2\out\worker\bundle.js:1709:13)
    at C:\Users\USER1\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.1.2\out\worker\bundle.js:1670:9
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\USER1\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.1.2\out\worker\bundle.js:81:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) code: 'MODULE_NOT_FOUND' }
`
Is it related to project folder structure ? this is the struct.
project\
   -Src\
       package.json
       nodeModules\
       main.js

**Comment by hbenl** [comment]
The problem is that you are using `electron-mocha` and not `mocha` itself, but this adapter is only designed to work with `mocha`, sorry.
You could try setting `mochaExplorer.mochaPath` to the path of the `electron-mocha` package, but that would only work if `electron-mocha` exports the same API for running tests programmatically as `mocha`, which is unlikely.
If this doesn't work, you could create a [worker script](https://github.com/hbenl/vscode-mocha-test-adapter/blob/master/src/worker/main.ts) and use it with `mochaExplorer.launcherScript`, but that would be a lot of work...

**Comment by ssrakesh** [comment]
Thanks for your time in replaying.
I understand adapter only works with "mocha"

I just tried with `"mochaExplorer.mochaPath": "node_modules/electron-mocha/bin/electron-mocha"`
this gave error 

```
TypeError: Cannot read property 'bdd' of undefined
    at patchMocha (C:\Users\[USER]\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.1.2\out\worker\bundle.js:743:64)
    at execute (C:\Users\[USER]\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.1.2\out\worker\bundle.js:1699:13)
    at C:\Users\[USER]\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.1.2\out\worker\bundle.js:1670:9
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\[USER]\.vscode\extensions\hbenl.vscode-mocha-test-adapter-2.1.2\out\worker\bundle.js:81:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
I am not asking you to fix or spend time to resolve this, but if I can try something to resolve this here let me know

**Comment by ssrakesh** [comment]
Thanks for help.

Setting monkeyPatch": false, got another issue.

So as a quick solution, I moved all the initialization of electron and object initialization code into 
before() hook function.
This made the toolbar load. however It does not run the tests with electron dependency.
But I think this is fine for now.

I also able to refactor some classes remove electron.app dependency. I think this should be right method for any classes which does not have ui or render process
