### ISSUE TITLE
Can't determine the result of tests written using mocha-param

### ISSUE THREAD

**Issue by MostlyArmless** [hbenl/vscode-mocha-test-adapter#78]
If you try to run tests written using mocha-param in the Test Explorer, the pass/fail state isn't shown, only a grey hazard symbol.

sample test code:
```TypeScript
const expect = require( 'chai' ).expect;
let itParam = require( 'mocha-param' );

interface TestDatum
{
    input: number;
    expectedOutput: boolean;
}

const testData: TestDatum[] = [
    {
        input: 1,
        expectedOutput: false
    },
    {
        input: 2,
        expectedOutput: true
    }
];

describe( 'ExampleTestSuite', () =>
{
    it( 'Normal mocha test', () =>
    {
        console.log( `This test runs just fine.` );
        expect( 1 ).to.eql( 1 );
    } );

    itParam( 'Dummy Parameterized tests', testData, ( value: TestDatum ) =>
    {
        const output = value.input > 1 ? true : false;
        expect( output ).to.equal( value.expectedOutput );
    } );
} );
```

Test Explorer results:
![image](https://user-images.githubusercontent.com/9409476/70678682-08462e80-1c50-11ea-83c4-7efb4fe857ba.png)

**Comment by hbenl** [comment]
The issue is that there are multiple tests with the same name and the name is used to identify the tests. So when Mocha tells Test Explorer that the test called "Dummy Parameterized tests" has passed / failed, Test Explorer doesn't know which test Mocha is talking about.
Test Explorer should show a warning message when you click on a test that doesn't have a unique name, but that message is never shown due to a bug in Test Explorer, which I will fix soon.
To make your test names unique you could use the corresponding [mocha-param feature](https://github.com/mikejsdev/mocha-param#add-the-values-being-tested-into-the-test-descriptions) or you could do it without mocha-param:
```javascript
for (const value of testData) {
    it('Dummy Parameterized tests #' + value.input, () => {
        const output = value.input > 1 ? true : false;
        expect( output ).to.equal( value.expectedOutput );
    });
}
```

**Comment by leoseccia** [comment]
I had the same issue because of this (tests with the same name) but what was happening was very misleading and took me a while to figure out what was going on...

My tests all ran successfully from the terminal so the issue was solely with test explorer.
My tests use `chai` in ts like so: `import { expect } from 'chai';`
When I ran my tests I was getting the error `ReferenceError: expect is not defined` for all instances where the name of the test was the same.

**Comment by hbenl** [comment]
I have made the warning about tests with the same ID more prominent in version 2.16.0 of Test Explorer. Hopefully this will make this issue less confusing.
