### ISSUE TITLE
The worker process finished with code null and signal SIGABRT

### ISSUE THREAD

**Issue by peni4142** [hbenl/vscode-mocha-test-adapter#85]
### The problem

I get the Error "The worker process finished with code null and signal SIGABRT" while loading the tests.

I working on an Ubuntu distribution of Linux. Because that is a project on my own it is open source and I made a branch for you so you can comprehend it easily.

Branch: https://github.com/peni4142/work-as-two/tree/mocha-exploror-problem

Thank you for your help :-)

### My settings anyway:

```
    "mochaExplorer.files": "src/**/*.test.ts",
    "mochaExplorer.require": "ts-node/register",
    "mochaExplorer.nodePath": "/snap/bin/node", // default has the same problem
    "mochaExplorer.monkeyPatch": false
```

**Comment by hbenl** [comment]
I couldn't reproduce the problem, but my first guess would be that the snap-packaged version of node may be a problem. Try setting `"mochaExplorer.nodePath": null` - this will use the version of node bundled with VS Code.
I also had to set `"mochaExplorer.ui": "tdd"` and change the name of one of the tests so that it's different from the other (Mocha Explorer needs the test names in a file to be unique so that it knows which test result belongs to which test).

**Comment by peni4142** [comment]
Yeah that worked for me : `"mochaExplorer.nodePath": null`.
I already tried `"mochaExplorer.nodePath": "null"`  before asking for help :-)
Sometimes I am a real idiot :-)

Thank you very much.
