### ISSUE TITLE
How to run mochawesome as part of test?

### ISSUE THREAD

**Issue by GregFinzer** [hbenl/vscode-mocha-test-adapter#89]
How do I run mochawesome for reporting as part of the test run?

Here is that I have for my .mocharc.json

```json
{
    "extension": ["js"],
    "package": "./package.json",
    "timeout": 0,
    "watch-files": ["./lib/*.js"],
    "reporter": "mochawesome",
    "reporter-options" : "reportDir=TestResults"
}
```

**Comment by GregFinzer** [comment]
Currently with this configuration it produces no output when the tests are run from the test explorer.

**Comment by gfinzerScotts** [comment]
I am able to run at the command line with this current configuration but the test explorer is not picking it up:

`{
    "extension": ["js"],
    "package": "./package.json",
    "timeout": 0,
    "watch-files": ["./lib/*.js"],
    "reporter": "mochawesome",
    "reporterOption" : "reportDir=./TestResults,timestamp=true,reportFilename=report"
}`

**Comment by hbenl** [comment]
This extension does not support other reporters (like mochawesome). It uses its own reporter that sends the test results to the Test Explorer and unfortunately I haven't found a way to use more than one reporter in Mocha.
I will add this to the documentation.

**Comment by 4ekki** [comment]
@hbenl, https://www.npmjs.com/package/mocha-multi-reporters allows to use multiple reporters. F.e., the following will allow me to get regular `spec` report, while with producing junit and allure results as well:

.mocharc.js: 
``` 
...
reporter: 'mocha-multi-reporters',
reporterOptions: {
    configFile: './reporterConfig.json',
}
...
```
reporterConfig.json: 
```
{
  "reporterEnabled": "spec, mocha-junit-reporter, mocha-allure-reporter",
  "mochaJunitReporterReporterOptions": {
    "mochaFile": "test-results.xml"
  },
  "mochaAllureReporterReporterOptions": {
    "targetDir": "allure-results"
  }
}
```

I ended up in this thread cause I want to run tests from VS Code, while generating allure report in the same time to get detailed logs there. This is not possible now, because allure requires its own reporter, and when I'm running tests from VSCode, this reporter is replaced by `vscode-mocha-test-adapter`'s one. 
My suggestion is to add a possiblility to integrate with `mocha-multi-reporters`. F.e., it could be a property `mochaExplorer.mochaMultiReportersConfig`, specifying path to reporterConfig.json. If this property is defined, extension simply adds its own reporter to `reporterConfig.json`.`reporterEnabled` array on launch. What do you think?

**Comment by 4ekki** [comment]
@hbenl ?
